# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 17:06
from __future__ import unicode_literals

from django.db import migrations, models
import sample.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20, validators=[sample.validators.validate_first_name])),
                ('last_name', models.CharField(max_length=20, validators=[sample.validators.validate_last_name])),
            ],
        ),
    ]
